"""LIMS urls."""

from django.urls import path

from . import views

app_name= 'lims'
urlpatterns = [
    path('', views.index, name="index"),
    path('clients/', views.clients, name="clients"),
    path('clients/<int:id_cliente>/', views.client, name="client"),
    path('add_client/', views.add_client, name="add_client"),
    path('clients/<int:id_cliente>/add_legal_representative/', views.client_add_legal_representative, name="client_add_legal_representative"),
    path('clients/<int:id_cliente>/add_contact/', views.client_add_contact, name="client_add_contact"),
    path('clients/<int:id_cliente>/add_sample_point/', views.client_add_sample_point, name="client_add_sample_point"),
    path('clients/<int:id_cliente>/add_rca/', views.client_add_rca, name="client_add_rca"),
    path('clients/<int:id_cliente>/add_project/', views.client_add_project, name="client_add_project"),
    path('clients/<int:id_cliente>/add_project_cot/', views.client_add_project_cot, name="client_add_project_cot"),
    path('clients/<int:id_cliente>/add_project_cot_etfa/', views.client_add_project_cot_etfa, name="client_add_project_cot_etfa"),
    path('normas_ref/add_norma/', views.add_normas_ref, name="add_normas_ref"),
    path('normas_ref/', views.normas_ref, name="normas_ref"),
    path('methods/', views.methods, name="methods"),
    path('methods/add_method/', views.add_method, name="add_method"),
    path('containers/', views.containers, name="containers"),
    path('containers/add_container/', views.add_container, name="add_containers"),
    path('parameters/', views.parameters, name="parameters"),
    path('parameters/add_parameter/', views.add_parameter, name="add_parameter"),
    path('samples_type/', views.samples_type, name="samples_type"),
    path('samples_type/add_sample_type/', views.add_sample_type, name="add_sample_type"),
    path('etfa/', views.etfa, name="etfa"),
    path('etfa/add_etfa/', views.add_etfa, name="add_etfa"),
    path('etfa/delete_etfa/<str:parameter_id>/', views.delete_etfa, name="delete_etfa"),
    path('project/<str:project_id>/', views.project, name="project"),
    path('project_cot/<str:project_id>/', views.project_cot, name="project_cot"),
    path('project/<str:project_id>/add_service', views.add_service, name="add_service"),
    path('project_cot/<str:project_id>/add_service', views.add_service_cot, name="add_service_cot"),
    path('project/<str:project_id>/add_service_etfa', views.add_service_etfa, name="add_service_etfa"),
    path('service/<str:service_id>/', views.service, name="service"),
    path('service/<str:service_id>/clone_service', views.clone_service, name="clone_service"),
    path('service/<str:service_id>/add_service_parameter', views.add_service_parameter, name="add_service_parameter"),
    path('service/<str:service_id>/add_service_parameter_etfa', views.add_service_parameter_etfa, name="add_service_parameter_etfa"),
    path('service/<str:service_id>/edit_sample_code/', views.edit_sample_code, name='edit_sample_code'),
    path('parameter/<str:parameter_id>/', views.edit_sample_parameter, name="edit_sample_parameter"),
    path('service_parameters/', views.service_parameters, name="service_parameters"),
    path('discarded_service_parameter/<str:parameter_id>/', views.service_parameter_dropped, name="service_parameter_dropped"),
    path('service_parameters_filter/', views.service_parameters_filter, name="service_parameters_filter"),
    path('discarded_service_parameters/', views.discarded_service_parameters, name="discarded_service_parameters"),
    path('discarded_service_parameters_filter/', views.discarded_service_parameters_filter, name="discarded_service_parameters_filter"),
    path('projects/', views.projects, name="projects"),
    path('services/', views.services, name="services"),
    path('batches/', views.batches, name="batches"),
    path('batches/add_batch', views.add_batch, name="add_batch"),
    path('batch/<str:batch_id>/', views.batch, name="batch"),
    path('export/<str:username>/', views.export_data_to_excel, name='export_data'),
    path('export_data_project/<str:project_id>/', views.export_data_project_to_excel, name='export_data_project'),
    path('project_client/<str:project_id>/', views.project_client, name="project_client"),
    path('grafico/<str:service_id>/', views.grafico, name='grafico'),
    ]
