# Generated by Django 4.1.4 on 2023-01-04 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=200, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=10, unique=True)),
                ('actividad', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Envase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('volumen', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=100)),
                ('preservante', models.CharField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Metodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NormaDeReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('norma', models.CharField(max_length=254, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParametroEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensayo', models.CharField(max_length=254)),
                ('codigo', models.CharField(max_length=254, unique=True)),
                ('metodo', models.CharField(max_length=254)),
                ('LDM', models.FloatField()),
                ('LCM', models.FloatField()),
                ('unidad', models.CharField(max_length=20)),
                ('tipo_de_muestra', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParametroGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensayo', models.CharField(max_length=254, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lims.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('codigo_muestra', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('punto_de_muestreo', models.CharField(max_length=200)),
                ('tipo_de_muestra', models.CharField(max_length=200)),
                ('fecha_de_muestreo', models.DateField()),
                ('envases', models.TextField()),
                ('fecha_de_recepción', models.DateField()),
                ('norma_de_referencia', models.CharField(max_length=254)),
                ('rCA', models.CharField(max_length=254)),
                ('etfa', models.BooleanField()),
                ('muestreado_por_algoritmo', models.CharField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(max_length=100)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lims.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='RepresentanteLegalCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lims.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='RCACliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rca_asociada', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lims.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoDeMuestreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lims.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ParametroDeMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_inicio', models.DateTimeField()),
                ('fecha_de_terminado', models.DateTimeField()),
                ('resultado', models.FloatField()),
                ('factor_de_dilucion', models.IntegerField()),
                ('resultado_final', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(max_length=100)),
                ('parametro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lims.parametroespecifico')),
                ('responsable_de_analisis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='ETFA',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(max_length=100)),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.parametroespecifico')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lims.cliente')),
            ],
        ),
    ]
