# Generated by Django 4.1.4 on 2023-01-09 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParametroGlobal',
        ),
        migrations.AlterField(
            model_name='parametrodemuestra',
            name='creator_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parametrodemuestra',
            name='factor_de_dilucion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametrodemuestra',
            name='fecha_de_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametrodemuestra',
            name='fecha_de_terminado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametrodemuestra',
            name='responsable_de_analisis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parametrodemuestra',
            name='resultado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametrodemuestra',
            name='resultado_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='envases',
            field=models.TextField(blank=True, null=True),
        ),
    ]
