# Generated by Django 4.1.4 on 2023-01-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
