# Generated by Django 4.1.4 on 2023-01-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_delete_parametroglobal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrodemuestra',
            name='parametro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.parametroespecifico'),
        ),
    ]
