# Generated by Django 4.1.4 on 2023-02-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_proyecto_tipodemuestra_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='TipoDeMuestra',
            new_name='tipo_de_muestra',
        ),
    ]
