# Generated by Django 4.1.4 on 2023-03-08 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_parametrodemuestra_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='representante_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lims.representantelegalcliente'),
        ),
    ]
