# Generated by Django 4.1.4 on 2023-01-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0003_servicio_editor_sample_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='codigo_muestra',
            field=models.CharField(max_length=50),
        ),
    ]
