# Generated by Django 4.1.4 on 2023-02-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0003_rename_tipodemuestra_proyecto_tipo_de_muestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='parametros_externos',
            field=models.ManyToManyField(related_name='parametros_analisis_externos', to='lims.parametroespecifico'),
        ),
    ]
