# Generated by Django 4.1.4 on 2023-02-24 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0004_proyecto_parametros_externos'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarDeMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lims.cliente')),
            ],
        ),
    ]
