# Generated by Django 4.1.4 on 2023-01-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0004_parametrodemuestra_codigo_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='cliente',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
