# Generated by Django 4.1.4 on 2023-01-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0004_alter_servicio_codigo_muestra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='codigo_muestra',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
