# Generated by Django 4.1.4 on 2023-03-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0005_alter_servicio_rca'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='observacion_de_recepcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
