# Generated by Django 4.1.4 on 2023-01-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0005_alter_servicio_codigo_muestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametrodemuestra',
            name='ensayo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
