# Generated by Django 4.1.4 on 2023-01-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0005_servicio_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametroespecifico',
            name='LCM',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametroespecifico',
            name='LDM',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
