# Generated by Django 4.1.4 on 2023-02-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0005_lugardemonitoreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
