# Generated by Django 4.1.4 on 2023-01-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_alter_parametroespecifico_lcm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametroespecifico',
            name='LCM',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parametroespecifico',
            name='LDM',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
