# Generated by Django 4.1.4 on 2023-02-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_servicio_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(max_length=100)),
            ],
        ),
    ]
