# Generated by Django 4.1.4 on 2023-03-08 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_servicio_observacion_de_recepcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='norma_de_referencia',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='rCA',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='representante_legal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lims.representantelegalcliente'),
        ),
    ]
