# Generated by Django 4.1.4 on 2023-01-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0006_parametrodemuestra_ensayo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametroespecifico',
            name='codigo_etfa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
