# Generated by Django 4.1.4 on 2023-01-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0007_parametroespecifico_codigo_etfa'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='parametros_cotizados',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lims.parametroespecifico'),
        ),
    ]
