# Generated by Django 4.1.4 on 2023-01-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0007_alter_parametroespecifico_lcm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametroespecifico',
            name='unidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
