# Generated by Django 4.1.4 on 2023-01-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0008_alter_parametroespecifico_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='responsable',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
