# Generated by Django 4.1.4 on 2023-01-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0008_proyecto_parametros_cotizados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='parametros_cotizados',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='parametros_cotizados',
            field=models.ManyToManyField(blank=True, null=True, to='lims.parametroespecifico'),
        ),
    ]
