# Generated by Django 4.1.4 on 2023-02-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0008_rename_fecha_de_contenedores_servicio_fecha_de_contenedores_o_filtros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelodeserviciodefiltro',
            name='fecha_de_entrega_cliente',
        ),
        migrations.AddField(
            model_name='modelodeserviciodefiltro',
            name='parametros',
            field=models.ManyToManyField(to='lims.parametroespecifico'),
        ),
    ]
