# Generated by Django 4.1.4 on 2023-02-27 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0009_remove_modelodeserviciodefiltro_fecha_de_entrega_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelodeserviciodefiltro',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lims.cliente'),
        ),
        migrations.AlterField(
            model_name='modelodeserviciodefiltro',
            name='norma_de_referencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lims.normadereferencia'),
        ),
        migrations.AlterField(
            model_name='modelodeserviciodefiltro',
            name='rCA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lims.rcacliente'),
        ),
    ]
