# Generated by Django 4.1.4 on 2023-01-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0009_remove_proyecto_parametros_cotizados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='cotizado',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='etfa',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
