# Generated by Django 4.1.4 on 2023-03-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0010_alter_cliente_actividad_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envase',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='envase',
            name='preservante',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='envase',
            name='volumen',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
