# Generated by Django 4.1.4 on 2023-02-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0010_alter_modelodeserviciodefiltro_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='etfa',
            field=models.BooleanField(default=False),
        ),
    ]
