# Generated by Django 4.1.4 on 2023-02-09 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0010_proyecto_cotizado_proyecto_etfa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('codido', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='parametrodemuestra',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='parametros_cotizados',
            field=models.ManyToManyField(to='lims.parametroespecifico'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='parametrodemuestra',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lims.batch'),
        ),
    ]
