# Generated by Django 4.1.4 on 2023-03-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0011_alter_servicio_etfa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha_de_contenedores_o_filtros',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_de_entrega_cliente',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_de_muestreo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_de_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
