# Generated by Django 4.1.4 on 2023-03-02 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0012_alter_servicio_fecha_de_contenedores_o_filtros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='parametros_cotizados',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='parametros_externos',
        ),
    ]
