# Generated by Django 4.1.4 on 2023-03-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0013_alter_batch_responsable_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='dias_habiles',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
