# Generated by Django 4.1.4 on 2023-02-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0013_batch_created_batch_creator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='parametro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
