# Generated by Django 4.1.4 on 2023-03-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0013_remove_proyecto_parametros_cotizados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='parametros_cotizados',
            field=models.ManyToManyField(to='lims.parametroespecifico'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='parametros_externos',
            field=models.ManyToManyField(related_name='parametros_analisis_externos', to='lims.parametroespecifico'),
        ),
    ]
