# Generated by Django 4.1.4 on 2023-03-13 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0014_servicio_dias_habiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelodeserviciodefiltro',
            name='responsable',
        ),
        migrations.AlterField(
            model_name='modelodeserviciodefiltro',
            name='norma_de_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lims.normadereferencia'),
        ),
        migrations.AlterField(
            model_name='modelodeserviciodefiltro',
            name='rCA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lims.rcacliente'),
        ),
    ]
