# Generated by Django 4.1.4 on 2023-03-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0014_proyecto_parametros_cotizados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
