# Generated by Django 4.1.4 on 2023-03-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0015_alter_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactocliente',
            name='rut',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
