# Generated by Django 4.1.4 on 2023-02-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0015_batch_responsable_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='responsable',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
