# Generated by Django 4.1.4 on 2023-02-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0016_batch_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametroDeMuestraDescartada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('codigo_servicio', models.CharField(max_length=100)),
                ('parametro', models.CharField(max_length=100)),
                ('responsable_de_analisis', models.CharField(max_length=100)),
                ('fecha_de_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_de_terminado', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.FloatField(blank=True, null=True)),
                ('factor_de_dilucion', models.IntegerField(blank=True, null=True)),
                ('resultado_final', models.FloatField(blank=True, null=True)),
                ('peso_inicial', models.FloatField(blank=True, null=True)),
                ('peso_final', models.FloatField(blank=True, null=True)),
                ('ensayo', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField()),
                ('dropped', models.DateTimeField(auto_now_add=True)),
                ('creator_user', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='parametrodemuestra',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
