# Generated by Django 4.1.4 on 2023-02-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0017_parametrodemuestradescartada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parametrodemuestradescartada',
            old_name='dropped',
            new_name='discarded',
        ),
        migrations.AddField(
            model_name='parametrodemuestradescartada',
            name='discarder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parametrodemuestradescartada',
            name='batch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
