# Generated by Django 4.1.4 on 2023-02-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0019_alter_parametrodemuestradescartada_batch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ETFA',
        ),
    ]
