# Generated by Django 4.1.4 on 2023-02-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0020_delete_etfa'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametroespecifico',
            name='acreditado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
