# Generated by Django 4.1.4 on 2023-02-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0021_parametroespecifico_acreditado'),
    ]

    operations = [
        migrations.AddField(
            model_name='normadereferencia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
